package com.revature.cachemoney.backend.beans.services;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import com.revature.cachemoney.backend.beans.models.Account;
import com.revature.cachemoney.backend.beans.models.User;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit.jupiter.SpringExtension;
import java.util.LinkedList;
import java.util.List;

@ExtendWith(SpringExtension.class)
@SpringBootTest
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class AccountServiceTest {
    @Autowired
    AccountsService accountsService;

    @Autowired
    private UsersService usersService;
    
    private User tempUser;

    private List<Account> validAccounts;

    @BeforeEach
    void populateDBWithUserandAccounts(){
        tempUser = new User("Hank", "Hill", "hankaccounthill@gmail.com", "abcd1234", "accounttest");
        usersService.postUser(tempUser);

        // Create accounts (They dont currently have a valid user model under attribute "userId")
        Account checkingAcc = new Account("checking");
        Account savingsAcc = new Account("savings");
        Account checkingAccWithNickname = new Account("checking", "secret account");

        //populate userId with a user that exists in database
        checkingAcc.setUserId(tempUser);
        savingsAcc.setUserId(tempUser);
        checkingAccWithNickname.setUserId(tempUser);

        // add accounts to list.
        validAccounts = new LinkedList<>();
        validAccounts.add(checkingAcc);
        validAccounts.add(savingsAcc);
        validAccounts.add(checkingAccWithNickname);

        // persist accounts to database
        for (Account validAcc : validAccounts){
            accountsService.postAccount(validAcc);
        }

    }

    @AfterEach
    void deleteDBData(){

        accountsService.deleteAllAccounts();
        usersService.deleteAllUsers();

        // must be set to null because after models are persisted
        // these variables will now contain an ID value that was
        // generated by the database.

        validAccounts = null;
        tempUser = null;

    }



    @Test
    void getAllAccounts() {
        assertEquals(3, accountsService.getAllAccounts().size());
    }

    @Test
    void getAccountByID() {

        List<Account> accountListFromDB = accountsService.getAllAccounts();

        for (Account currAcc : accountListFromDB){
            assertTrue(accountsService.getAccountByID(currAcc.getAccountId()).isPresent());
        }

        assertFalse(accountsService.getAccountByID(0).isPresent());

    }




    @Test
    void deleteAccountById() {
        List<Account> accountListFromDB = accountsService.getAllAccounts();

        for (Account currAcc : accountListFromDB){
            assertTrue(accountsService.deleteAccountById(currAcc.getAccountId()));
        }

        assertFalse(accountsService.deleteAccountById(0));

    }




    @Test
    void getTransactionsById() {
    }


    @Nested
    class TestPostAccount{
        @BeforeEach
        void populateDB(){
            if (usersService.getAllUsers().size() != 0) {
                if (accountsService.getAllAccounts().size() != 0){
                    accountsService.deleteAllAccounts();
                }
                usersService.deleteAllUsers();
                tempUser = new User("Hank", "Hill", "hankaccounthill@gmail.com", "abcd1234", "accounttest");
                usersService.postUser(tempUser);
            }else{
                tempUser = new User("Hank", "Hill", "hankaccounthill@gmail.com", "abcd1234", "accounttest");
                usersService.postUser(tempUser);
            }
            if (accountsService.getAllAccounts().size() != 0){
                accountsService.deleteAllAccounts();
            }


        }

        @AfterEach
        void deleteDBData(){
            accountsService.deleteAllAccounts();
            usersService.deleteAllUsers();

            tempUser = null;

        }

        @Test
        void postAccount() {
            System.out.println("account service test postaccount");

            Account testChecking = new Account("checking");
            Account testIncorrectType = new Account("blahblah");
            testChecking.setUserId(tempUser);
            testIncorrectType.setUserId(tempUser);


            assertEquals(false, accountsService.postAccount(testIncorrectType));
            assertEquals(true, accountsService.postAccount(testChecking));


        }


    }

}